### Actualizar tarifa completa (PUT)
PUT http://localhost:4000/api/tarifas/1
Content-Type: application/json

{
  "nombre": "Tarifa Actualizada PUT",
  "regla_calculo": "Base",
  "valor_base": 200,
  "vigencia_desde": "2033-01-01T00:00:00Z",
  "vigencia_hasta": "2033-12-31T23:59:59Z",
  "status": "active"
}

### Actualizar tarifa parcial (PATCH)
PATCH http://localhost:4000/api/tarifas/1
Content-Type: application/json

{
  "valor_base": 250
}
